4 add migration entity
elinarite/notification-service pull request #7
Opened 2023-10-18 11:41 UTC by elinarite

- Moved the Telegram token to environment variables and stored it in GitHub Secrets.
- Added dependencies for DB Postgres and Liquibase Migration.
- Set up LQ migration (SQL scripts for creating tables and populating with test data).
- Created Entity.
- Corrected exception output.
- Connected Postgres to GitHub actions, but didn't fully set it up as the SQL scripts need to be added to the GitHub repository first.

2023-10-18 11:57 UTC, raymank26 commented on src/main/resources/application.properties
> +bot.owner=1361169404
Don't share sensitive data.

2023-10-18 13:13 UTC, raymank26 requested changes

2023-10-18 13:13 UTC, raymank26 commented on src/main/resources/db/changelog/v.0.1.0/ddl-create-tables-0.1.0.sql
> +    id            bigint generated by default as identity
should be properly formatted

2023-10-18 13:13 UTC, raymank26 commented on src/main/resources/db/changelog/v.0.1.0/ddl-create-tables-0.1.0.sql
> +-- create or replace function update_timestamp()
these comments should be deleted

2023-10-18 13:13 UTC, raymank26 commented on src/main/resources/db/changelog/v.0.1.0/test-data-0.1.0.sql
> +
Reduce a number of empty strings.

2023-10-18 13:13 UTC, raymank26 commented on .github/workflows/build_maven.yml
> +#      - name: Настройка базы данных
Remove these comments.

2023-10-18 13:13 UTC, raymank26 commented on .github/workflows/build_maven.yml
> +
Not sure why Postgres and Telegram token is needed just to build the project. Could you clarify?

2023-10-18 13:13 UTC, raymank26 commented on src/main/resources/db/changelog/v.0.1.0/ddl-create-schema-0.1.0.sql
> +    CREATE SCHEMA IF NOT EXISTS notification_bot;
formatting

2023-10-18 13:13 UTC, raymank26 commented on src/main/java/com/example/notificationservice/webSocket/WebSocketClient.java
> +            System.err.println("Error starting WebSocket listener: " + e);
Please use a logging library like `slf4j`.

2023-10-18 18:41 UTC, Sergii-Kozhushko commented on src/main/resources/application.properties
> +spring.datasource.username=postgres
spring.datasource.username наверное тоже стоит вынести в переменные окружения, также можно указать дефолтные значения через двоеточие

2023-10-18 18:42 UTC, Sergii-Kozhushko commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
диалект можно не указывать, его указывают в специфических случаях

2023-10-18 18:46 UTC, Sergii-Kozhushko commented on src/main/resources/db/changelog/v.0.1.0/ddl-create-tables-0.1.0.sql
> +CREATE SCHEMA IF NOT EXISTS notification_bot;
Создавать схему в чейнджлоге ликвибейза не имеет смысла. если указано, что ликвибейз должен использовать схему "notification_bot" (spring.liquibase.default-schema=notification_bot), то схема должна быть создана ДО запуска ликвибейза, чтобы ликбибейз мог запуститься. То есть нужно создавать ее вручную, или устраивать еще какую-нибудь хитрую схему. Поэтому в этой строчке нет смысла

2023-10-18 18:47 UTC, Sergii-Kozhushko approved these changes
Оставил комментарии отдельно. Пожелание - поменьше изменений в одном пулл реквесте

2023-10-18 19:05 UTC, cyberkost approved these changes

2023-10-18 19:05 UTC, cyberkost commented on src/main/java/com/example/notificationservice/model/Notification.java
> +
Can use @Data instead @Getter @Setter @AllArgsConstructor @NoArgsConstructor?

2023-10-18 19:06 UTC, cyberkost commented on src/main/java/com/example/notificationservice/model/User.java
> +
Can use @Data instead @Getter @Setter @AllArgsConstructor @NoArgsConstructor?

2023-10-18 19:07 UTC, cyberkost approved these changes
Nice work

2023-10-19 10:18 UTC, elinarite commented on src/main/java/com/example/notificationservice/model/Notification.java
> +
Я отметила это задание как "todo" из-за аннотации @Data, так как пока не убеждена в правильности её применения. Но благодарю за совет, я посмотрю этот момент позже, возможно, заменю на @Data, но сначала мне нужно будет провести тесты.

2023-10-19 10:23 UTC, elinarite commented on .github/workflows/build_maven.yml
> +
I removed the Telegram token, and I will add Testcontainer in the next PR.

2023-10-19 10:59 UTC, elinarite commented
I've made corrections based on all the feedback. I've left comments on the adjustments I plan to make in the future. I've entirely removed logging from the application.properties. Additionally, I set up a basic logging file and incorporated the @Slf4j annotation.

2023-10-19 11:11 UTC, raymank26 commented on src/main/java/com/example/notification_service/webSocket/WebSocketClient.java
> +            log.info("Error starting WebSocket listener: " + e);
log.info("Error starting WebSocket listener: ", e);

2023-10-19 11:29 UTC, raymank26 commented on src/main/java/com/example/notification_service/webSocket/WebSocketClient.java
> +package com.example.notification_service.webSocket;
You can just use "notification".

2023-10-19 12:31 UTC, merged